### ISSUE TITLE
[Question/Suggestion] Why use configs for recipes rather than `ResourcePackActivationType.DEFAUL_...`

### ISSUE THREAD

**Issue by supersaiyansubtlety** [spacegoat3/BuildableCampfire#1]
If you changed your recipe registrations `DEFAULT_ENABLED` and `DEFAULT DISABLED` rather than `ALWAYS_ENABLED`, they could be en-/dis-abled without having to restart the game, and you wouldn't need configs for the recipes. 

If you're worried about users not finding them, you can always put a comment in your config and mod menu screen.

**Comment by spacegoat3** [comment]
1 - This project was mostly an experiment that I made to learn more about configs, so the main goal in my head was to create a project that has a config.

2 - I thought a config would look better instead of multiple datapacks filling the screen. Since the mod already has a lot of recipes and we are planning to add more, it would be hard for users to find the recipes they are looking for.

3 - With the config options, users can disable huge amounts of similar recipes, those are called "Recipe Categories". So if they don't want, for example, Rotten Flesh to Leather Recipes, they can just disable them with one click and sometimes some writing, other than disabling all of them out piece by piece.

But still, this is also another way to do it and a user's experience is more accurate than mine. So, if you think it would be easier to use this mod if it was like what you said, then I will gladly change it.

I am also a new developer and comments like these help me a lot, so thank you for taking your time to write this and trying to correct my mistake. Have a nice day :]

**Comment by supersaiyansubtlety** [comment]
Oh I wouldn't say it was a mistake, both are valid approaches. I also didn't know about your plans to add more recipes. 

It's quite possible other users would prefer config options. I'm personally used to datapacks so it wouldn't be confusing or inconvenient for me, but it very well might be for other users.

**Comment by spacegoat3** [comment]
I can make a different branch that works the way you said and release it if you want?

**Comment by supersaiyansubtlety** [comment]
Oh don't worry about it. 
And implement the recipe config for this mod however you prefer, I was just making this suggestion in case you hadn't considered this approach.

**Comment by spacegoat3** [comment]
I made and released it: [https://modrinth.com/mod/buildable-campfire/version/hvb62J5F](https://modrinth.com/mod/buildable-campfire/version/hvb62J5F). Built-in resourcepacks can now get enabled/disabled by both config and Datapacks Menu. 
Thank you for the idea again, this way users can disable resourcepacks without closing the game.
